DELIMITER $$
CREATE PROCEDURE SelectCustomersSum()
BEGIN 
SELECT CUST_NAME,GRADE FROM (SELECT CUST_NAME,GRADE,SUM(OPENING_AMT+RECEIVE_AMT) AS sum_amt from customer GROUP BY CUST_NAME,GRADE having sum_amt>10000) b ; 
END $$
DELIMITER ;

Call SelectCustomersSum();
